<a href="https://colab.research.google.com/github/TBGhorbanpour/Social-Awareness/blob/main/Initial_Cleanup_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install https://github.com/sobhe/hazm/archive/master.zip --upgrade

Collecting https://github.com/sobhe/hazm/archive/master.zip
  Downloading https://github.com/sobhe/hazm/archive/master.zip
     \ 3.4 MB 7.5 MB/s 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting flashtext<3.0,>=2.7 (from hazm==0.12.1)
  Downloading flashtext-2.7.tar.gz (14 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: huggingface-hub>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from hazm==0.12.1) (1.33.0)
Requirement already satisfied: nltk<4.0.0,>=3.9.0 in /usr/local/lib/python3.13/dist-packages (from hazm==0.12.1) (3.9.1)
Collecting python-crfsuite<0.10.0,>=0.9.12 (from hazm==0.12.1)
  Downloading python_crfsuite-0.9.12-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.67.3 in /usr/local/lib/python3.13/dist-packages (from hazm==0.12.1) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.25.0->hazm==0.12.1) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.25.0->hazm==0.12.1) (4.2.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.25.0->hazm==0.12.1) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.25.0->hazm==0.12.1) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.25.0->hazm==0.12.1) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.25.0->hazm==0.12.1) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.25.0->hazm==0.12.1) (6.0.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.25.0->hazm==0.12.1) (4.16.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk<4.0.0,>=3.9.0->hazm==0.12.1) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk<4.0.0,>=3.9.0->hazm==0.12.1) (2025.11.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.25.0->hazm==0.12.1) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.25.0->hazm==0.12.1) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.25.0->hazm==0.12.1) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.25.0->hazm==0.12.1) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.25.0->hazm==0.12.1) (0.16.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->nltk<4.0.0,>=3.9.0->hazm==0.12.1) (3.1.2)
Downloading python_crfsuite-0.9.12-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 17.4 MB/s eta 0:00:00
Building wheels for collected packages: hazm, flashtext
  Building wheel for hazm (pyproject.toml) ... done
  Created wheel for hazm: filename=hazm-0.12.1-py3-none-any.whl size=887193 sha256=5fb30bc1882956c91909130d85bbf411017bed50d9cd087d2d3118e82a598a21
  Stored in directory: /tmp/pip-ephem-wheel-cache-i_pjei2o/wheels/53/44/ee/41158b0cbc5207b1cec003d4cc8a85701368f91406a25f0d2c
  Building wheel for flashtext (setup.py) ... done
  Created wheel for flashtext: filename=flashtext-2.7-py2.py3-none-any.whl size=9371 sha256=68401648aefc94f890a33e8b98e56f6ff56210c00d4bf1345dc9f13de47be471
  Stored in directory: /root/.cache/pip/wheels/be/12/c9/228313ff5cb722777830302f1d4136de4129932e6a0354c056
Successfully built hazm flashtext
Installing collected packages: flashtext, python-crfsuite, hazm
Successfully installed flashtext-2.7 hazm-0.12.1 python-crfsuite-0.9.12

In [2]:
!pip install demoji langdetect

Collecting demoji
  Downloading demoji-2.0.0-py3-none-any.whl.metadata (5.9 kB)
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 14.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from langdetect) (1.17.0)
Downloading demoji-2.0.0-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.4/43.4 kB 3.3 MB/s eta 0:00:00
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993335 sha256=3915999e8d9b077fc62f31d5a441976712fa20429a9e029b0e463da3d63755b5
  Stored in directory: /root/.cache/pip/wheels/eb/87/25/2dddf1c94e1786054e25022ec5530bfed52bad86d882999c48
Successfully built langdetect
Installing collected packages: langdetect, demoji
Successfully installed demoji-2.0.0 langdetect-1.0.9

In [3]:
import pandas as pd
import re

In [4]:
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

Mounted at /content/drive

**Number of raw dataset records**

In [5]:
df = pd.read_csv('/content/drive/MyDrive/Thesis/Data/Data/Raw_Data/rawData.csv')

In [6]:
num_records = len(df)
print(f"Number of records: {num_records-1}")

Number of records: 205664

**Language Detection**

In [7]:
from langdetect import detect
import pandas as pd

df["language"] = ''

for index, row in df.iterrows():
    tweet = row["Tweet"]
    if len(tweet) > 2:  # Minimum length requirement
        try:
            lang = detect(tweet)
            df.at[index, "language"] = lang
        except:
            df.at[index, "language"] = "unknown"
    else:
        df.at[index, "language"] = "unknown"

df = df[df["language"] == "fa"]

In [8]:
num_records = len(df)
print(f"Number of Farsi records: {num_records-1}")

Number of Farsi records: 191540

***use the formal converter with Farsiyar outside of this notebook***

In [76]:
data = pd.read_csv('/content/drive/MyDrive/Thesis/Data/Data/Data_Paper/MainDB.csv')

In [77]:
data.shape

(191245, 12)

**Countries Filter**

In [78]:
data.drop(data[data['FormalTweet'].str.contains('اسکاتلند|اسکاندیناوی|افریقا|آذربایجان|آرژانتین|آفریقای جنوبی|آفریقای مرکزی|آلبانی|آلمان|آنتیگوا و باربودا|آندورا|آنگولا|اتریش|اتیوپی|اردن|ارمنستان|اریتره|ازبکستان|اسپانیا|استرالیا|استونی|اسرائیل|اسلوواکی|اسلوونی|افغانستان|اکوادور|الجزایر|السالوادور|امارات متحده عربی|امریکا|اندونزی|انگلستان|انگلیس|اوروگوئه|اوکراین|اوگاندا|ایتالیا|ایرلند|ایسلند|باربادوس|باهاما|بحرین|برزیل|برونئی|بریتانیا|بلاروس|بلژیک|بلغارستان|بلیز|بنگلادش|بنین|بوتان|بوتسوانا|بورکینافاسو|بوروندی|بولیوی|پاپوا گینه نو|پاراگوئه|پاکستان|پاناما|پرتغال|پرو|تاجیکستان|تانزانیا|تایلند|ترکمنستان|ترکیه|ترینیداد و توباگو|توگو|تونس|تونگا|تووالو|جامائیکا|جیبوتی|چاد|چک|چین|چین تایپه|دانمارک|دومنیکا|دومنیکن|روآندا|روسیه|رومانی|زئیر|زامبیا|زلاندنو|زیمباوه|ژاپن|سائوتومه و پرنسیپ|ساحل عاج|ساموای غربی|سان مارینو|سریلانکا|سلیمان|سنت کریستوفر و نویس|سنت لوسیا|سنت وینست و گرنادین|سنگاپور|سنگال|سوازیلند|سوئد|سودان|سورینام|سوریه|سومالی|سوئیس|سیرالئون|سیشل|شیلی|صربستان|عراق|عربستان سعودی|عمان|غنا|فرانسه|فنلاند|فیجی|فیلیپین|قبرس|قرقیزستان|قزاقستان|قطر|کامبوج|کامرون|کانادا|کرواسی|کره جنوبی|کره شمالی|کاستاریکا|کلمبیا|کنگو|کنیا|کوبا|کوت دیووار|کومور|کویت|کیپ ورد|کیریباس|گابون|گامبیا|گرانادا|گرجستان|گواتمالا|گویان|گینه|گینه استوائی|گینه بیسائو|لائوس|لاتوی|لبنان|لسوتو|ماسدونیا|ماداگاسکار|مالاوی|مالزی|مالدیو|مالی|مالتا|جزایر مارشال|ماریتانیا|ماریتیوس|مکزیک|ایالات فدرالی میکرونزیا|مولدوا|موناکو|مونگل|مونتنگرو|مراکش|موراکو|موزامبیک|میانمار|مجارستان|مصر|نامیبیا|نارو|نپال|نیوزیلند|نیکاراگوئه|نایجر|نیجریه|وانوآتو|واتیکان|ونزوئلا|ویتنام|هند|هندوراس|هلند|یمن|یونان|لندن|کربلا|نجف|اکراین|توکیو|امارات|کالیفرنیا|پاریس|عربستان|یوگوسلاوی')].index, inplace= True)
data.shape

(148600, 12)

***Cleaning***

In [79]:
class preprocess:
    def tlt(cls, intab, txt):
        return txt.translate({ord(k): v for k ,v, in zip(intab,outtab)})

    def handle_correct_alphabets(self, doc_string):
        multiple_subs=[
            (r'اً|اٌ|اٍ|أ|إ|ا|آ', r'ا'),
            (r'ی|ي|ی|ۍ|ے|ێ',r'ی'),
            (r'ﻜ|ﻚ|ك|ڪ|ک|ک',r'ک'),
            (r'(\n)+',r'\n'),
            (r'0|۰|٠',r'۰'),
            (r'1|۱|١',r'۱'),
            (r'2|۲|٢',r'۲'),
            (r'3|۳|٣',r'۳'),
            (r'4|۴|٤',r'۴'),
            (r'5|۵|٥',r'۵'),
            (r'6|۶|٦',r'۶'),
            (r'7|۷|٧',r'۷'),
            (r'8|۸|٨',r'۸'),
            (r'9|۹|٩',r'۹'),
        ]
        for old, new in multiple_subs:
            doc_string = re.sub(old, new, doc_string)
        return doc_string

    def handle_convert_punctuation(self, doc_string):
        # !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
        multiple_subs=[
            (r'[?|؟]',r'؟'),
            (r'[,|،|٬|٫]',r'،'),
            (r'[%|٪]',r'%')
        ]
        for item in multiple_subs:
            doc_string = re.sub(item[0], item[1], doc_string)
        return doc_string

    def clean(self, text,
              remove_email=True, remove_urls=True, remove_digits=True):

        text=self.handle_correct_alphabets(text)

        text=self.handle_convert_punctuation(text)

        #remove mentions , hashtag , urls
        if remove_urls:

            text = re.sub(r"(?:\@|#\S+|https?\://)\S+"," ",text)
            text = re.sub(r'(https?://\S+)|www\.\S+|\b\w+\.\w{2,3}/\S+|\b\w+\.\w{2,3}', '', text)
            text = re.sub(r'https://t\.co/\w+|@\w+|#\w+', '', text)
            text = re.sub(r'https://t\.co/\w+', '', text)


        #remove email
        if remove_email:
            text = re.sub(r"\b[\w.%+-]+@[\w.-]+\.[a-zA-Z]{2,6}\b"," ",text)

        #Remove number
        if remove_digits:
            text= re.sub(r"\d",'',text)

        #Seprate non persian characters or words from persian characters or words
        text = re.findall(r"[\dA-Za-z._]+|[^\dA-Za-z\W]+",text,re.UNICODE)
        text= ' '.join(word for word in text)

        #replace new line characters
        text= re.sub (r'[\r\n\r\n]+',' ',text)
        #text= re.sub('\r?\n',' . ',text)
        text= re.sub('-{3}',' ',text)
        text= re.sub('-{2}',' ',text)

        #replace three ... dots with one
        text= re.sub("\s*\.{3,}",' . ',text)
        text= re.sub("\s*\.{2,}",' . ',text)

        #می و نمی could be separate nouns and not prefix
        text = re.sub(r"\s+(ن?می)\s+",r' \1',text)

        # های و تر could be seprate nouns and not suffix
        #text = re.sub(r"\s+?(?(ن)ی)تر?\s+",r'\1',text)
        text = re.sub(r"\s+((ی) ی)ها\s+",r'\1',text)
        text = re.sub("\s+(تر(ین)?)\s+",r'\1 ',text)
        text = re.sub("\s+(تری?)\s+",r'\1 ',text)
        text = re.sub("\s+(های?)\s+",r'\1 ',text)
        text = re.sub("\s+(گیری)\s+",r'\1 ',text)

        #Aggressive punctuations
        text = re.sub(r"(!){2,}",r'\1',text)
        text = re.sub(r"(؟){2,}",r'\1',text)

        #replace more than one space
        text= re.sub("[ ]+",u' ',text)
        text = re.sub(r"([\n]+)[ \t]*",r'\1',text)

        #Remove Extended char
        text = re.sub(r"-+|_",r' ',text)

        #space after colon separate time part
        text = re.sub(r"([۰-۹]+):\s+([۰-۹]+)",r'\1:\2',text)

        #Remove tag
        p = re.compile(r'<.*?>')
        text = p.sub('', text)

        text.strip()

        return text

<>:72: SyntaxWarning: invalid escape sequence '\s'
<>:73: SyntaxWarning: invalid escape sequence '\s'
<>:81: SyntaxWarning: invalid escape sequence '\s'
<>:82: SyntaxWarning: invalid escape sequence '\s'
<>:83: SyntaxWarning: invalid escape sequence '\s'
<>:84: SyntaxWarning: invalid escape sequence '\s'
<>:72: SyntaxWarning: invalid escape sequence '\s'
<>:73: SyntaxWarning: invalid escape sequence '\s'
<>:81: SyntaxWarning: invalid escape sequence '\s'
<>:82: SyntaxWarning: invalid escape sequence '\s'
<>:83: SyntaxWarning: invalid escape sequence '\s'
<>:84: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_4598/4260023605.py:72: SyntaxWarning: invalid escape sequence '\s'
  text= re.sub("\s*\.{3,}",' . ',text)
/tmp/ipykernel_4598/4260023605.py:73: SyntaxWarning: invalid escape sequence '\s'
  text= re.sub("\s*\.{2,}",' . ',text)
/tmp/ipykernel_4598/4260023605.py:81: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub("\s+(تر(ین)?)\s+",r'\1 ',text)
/tmp/ipykernel_4598/4260023605.py:82: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub("\s+(تری?)\s+",r'\1 ',text)
/tmp/ipykernel_4598/4260023605.py:83: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub("\s+(های?)\s+",r'\1 ',text)
/tmp/ipykernel_4598/4260023605.py:84: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub("\s+(گیری)\s+",r'\1 ',text)

In [80]:
prep = preprocess()
data['FormalTweet'] = data['FormalTweet'].apply(lambda x: prep.clean(x))

In [81]:
data.head(5)

,Column1,ID,Date,Tweet,URL,Likes,Retweet,Replies,Source,FormalTweet,Keyword,language
0,0.0,1.561085e+18,2022-08-21 00:45:24,@berserukk همون که خاک هرمز بود دیگه؟!,https://twitter.com/farremaa/status/1561084506...,0.0,0.0,1.0,Android,همان که خاک هرمز بود دیگر,خاک هرمز,NaN
1,1.0,1.560507e+18,2022-08-19 10:30:12,@bbrdiya تاحالا نون توموشی به کسی که اولین بار...,https://twitter.com/yourpenpalfar/status/15605...,1.0,0.0,0.0,iPhone,تاحالا نان توموشی به کسی که اولین بارش امده بن...,خاک هرمز,NaN
2,2.0,1.560269e+18,2022-08-18 18:46:43,@zahrahp1998 سرنج\nبه معنی خاک سرخ\nوایب هرمز ...,https://twitter.com/alipaydarr/status/15602694...,0.0,0.0,1.0,iPad,سرنج به معنی خاک سرخ وایب هرمز گرفتم از تو,خاک هرمز,NaN
4,4.0,1.558559e+18,2022-08-14 01:28:32,@sina_mim خاک های رنگی جزیره هرمز 🙂,https://twitter.com/aarcomood/status/155855864...,1.0,0.0,1.0,Android,خاکهای رنگی جزیره هرمز,خاک هرمز,NaN
5,5.0,1.558507e+18,2022-08-13 22:04:51,@sina_mim من خاک آوردم، خاک جزیره ی هرمز,https://twitter.com/Abi_in_dream/status/155850...,1.0,0.0,0.0,iPhone,من خاک اوردم خاک جزیره ی هرمز,خاک هرمز,NaN

In [82]:
data.shape

(148600, 12)

In [15]:
def remove_emojis(text):
    # Add error handling to handle non-string values
    if isinstance(text, str):
        return demoji.replace(text, "")
    else:
        return text

In [ ]:
import demoji
demoji.download_codes()
# Remove emojis from the 'Tweet' column
data['FormalTweet'] = data['FormalTweet'].apply(remove_emojis)

In [83]:
# Load the list of hashtags from the .txt file
with open('Removal_Hashtags.txt', 'r', encoding='utf-8') as file:
    hashtags = file.read().splitlines()

# Remove rows that contain the unwanted hashtags
for hashtag in hashtags:
    data = data[~data['FormalTweet'].str.contains(fr'#{hashtag}\b', case=False, na=False, regex=True)]
def remove_hashtags(text):
    if isinstance(text, str):
        text = re.sub(r'#\w+', '', text)
    return text
data['FormalTweet'] = data['FormalTweet'].apply(remove_hashtags)

In [84]:
data.shape

(148600, 12)

In [85]:
stop_words = []
with open('The_Final.txt', 'r') as file:
    for line in file:
        stop_words.append(line.strip())
# Function to remove stop words from a sentence
def remove_stopwords(sentence):
    # Tokenize the sentence into words or tokens
    tokens = sentence.split()  # Assuming space-separated tokens
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return ' '.join(filtered_tokens)

In [86]:
data['FormalTweet'] = data['FormalTweet'].apply(remove_stopwords)

In [87]:
data.shape

(148600, 12)

In [88]:
with open('SwearWords.txt', 'r', encoding='utf-8') as file:
  swear_words = [line.strip() for line in file]

#The function returns True/False
def contains_swear_word(sentence):
    if not isinstance(sentence, str):
        return False

    tokens = sentence.split()
    # Check if any word is in the swear words list
    # (Using .lower() here to make it case-insensitive)
    for word in tokens:
        if word.lower() in [sw.lower() for sw in swear_words]:
            return True # A swear word was found!

    return False # No swear words found
original_count = len(data)
data = data[~data['FormalTweet'].apply(contains_swear_word)]

print(f"Successfully removed {original_count - len(data)} records containing swear words.")
print(f"New total records: {len(data)}")

Successfully removed 397 records containing swear words.
New total records: 148203

In [89]:
data.shape

(148203, 12)

In [90]:
# 1. Load unrelated words
with open('UnrelatedWords.txt', 'r', encoding='utf-8') as file:
    unrelated_words = [line.strip() for line in file]

# 2. Function returns True/False
def contains_unrelated_word(sentence):
    if not isinstance(sentence, str):
        return False

    tokens = sentence.split()
    # Check if any word is in the unrelated words list
    for word in tokens:
        if word.lower() in [uw.lower() for uw in unrelated_words]:
            return True  # An unrelated word was found!

    return False  # No unrelated words found

# 3. Filter the DataFrame to keep only rows without unrelated words
original_count = len(data)
data = data[~data['FormalTweet'].apply(contains_unrelated_word)]

print(f"Successfully removed {original_count - len(data)} records containing unrelated words.")
print(f"New total records: {len(data)}")

Successfully removed 29904 records containing unrelated words.
New total records: 118299

In [91]:
data.shape

(118299, 12)

In [92]:
replacement_dict = {
    'بارون': 'باران',
    'اتیش': 'اتش',
    'میسوزه': 'می سوزد',
    'میگه': 'می گوید',
    'اتش سوزی': 'اتش‌سوزی',
    'میسوزد':'می سوزد',
    'طفا':'اطفا',
    'ابی':'اب',
    'ابهای':'اب',
    'خشکید':'خشک شد',
    'خشکانده':'خشک',
    'کشاورزا':'کشاورز',
    'اصفهانی':'اصفهان',
    'فرو نشست':'فرونشست',
    'محیط بان':'محیطبان',
    'کشاورزن':'کشاورز',
    'اسمون':'اسمان',
    'نیستا':'نیست',
    'درختا':'درخت',
    'ساهای':'سال های',
    'زیستی':'زیست',
    'وایر':'ویران',
    'نسلد':'نسل',
    'باسه':'باشد',
    'دامت':'دامنه',
    #'ازد':'ازادی',
    'بنابراظ':'',
    'ساله':'سال',
    'جهانی':'جهان',
    'جمعیتشون':'جمعیت',
    'انسان':'فرد',
    'اورمیه':'ارومیه',
    'سگا':'سگ',
    'سگها':'سگ',
    'سگهای':'سگ',
    'سگی':'سگ',
    'ادمها':'ادم',
    'الایندها':'الاینده',
    'شبا':'شب',
    'بابا':'پدر',
    'کشتن':'کشتار',
    'ازادییاد':'ازادی',
    'گرسنگی':'گرسنه',
    'ساکتند':'ساکت هستند',
    'استانی':'استان',
    'اسلامی':'اسلام',
    'اصفهانا':'اصفهان',
    'اصلی':'اصل',
    'اعتراضی':'اعتراض',
    'اقتصادی':'اقتصاد',
    'اقلیمی':'اقلیم',
    'الودگی':'الوده',
    'امنیتی':'امنیت',
    #'ایرانی':'ایران',
    'بدبختی':'بدبخت',
    'تعطیلی':'تعطیل',
    'حکومتی':'حکومت',
    'خبری':'خبر',
    'خداوند':'خدا',
    'خدایت':'خدا',
    'درختن':'درخت',
    'دزدی':'دزد',
    'دشمنی':'دشمن',
    'دولتی':'دولت',
    'زمینی':'زمین',
    'زندانی':'زندان',
    'زیبایی':'زیبا',
    'سالا':'سال',
    'شرقی':'شرق',
    'صنعتی':'صنعت',
    'علمی':'علم',
    'غذایی':'غذا',
    'غربی':'غرب',
    'فرهنگی':'فرهنگ',
    'فقیر':'فقر',
    #'محیطب':'محیطبان',############################################
    'متری':'متر',
    'قانونی':'قانون',
    'مردن':'مرده',
    'معدنی':'معدن',
    'مهاجرت':'مهاجر',
    'نابودی':'نابود',
    'نگرانی':'نگران',
    'گرونی':'گرون',
    'گرون':'گران',
    'گسترده':'گسترش',
    'اجرایی':'اجرا',
    'اخوندا':'اخوند',
    'ازادیواج':'ازادواج',
    'استانداری':'استاندار',
    'اصفهانها':'اصفهان',
    'جنگهداریداریداریا':'جنگلداری',#########check it on dataset
    'خونه':'خانه',
    'رییس':'رئیس',
    'سالست':'سال است',
    'سیلاب':'سیل',
    'محیطبانانان':'محیطبان',
    'معنی':'معنا',
    'منزل':'خانه',
    'مهمترن':'مهمتر هستند',
    'نفتی':'نفت',
    'نگهداریداریداری':'نگهداری',
    'نگهداریداریداریداری':'نگهداری',
    'وبختیاری':'بختیاری',
    'گرانی':'گرانس',
    'یادم':'یاد من',
    'ابش':'اب',
    'بارانی':'باران',
    'جنوبی':'جنوب',
    'جنگلی':'جنگل',
    'خواری':'خوار',
    'روستایی':'روستا',
    'صادرات':'صادر',
    'تاریخی':'تاریخ',
    'گرانس':'گران',
    'پراب':'اب',
    'خاکی':'خاک',
    'خبرنگار ':'خبر',
    'خطرناک':'خطر',
    'خوزستانی':'خوزستان',
    'سدسازی':'سد',
    'فصلی':'فصل',
    'قدیمی':'قدیم',
    'مهمتر':'مهم',
    'هرسال':'سال',
    'وزیر':'وزارت',
    'ویرانی':'ویران',
    'کشاورزی':'کشاورز',
    'گیاهی':'گیاه',
    'بیماری':'بیمار',
    'ریاست':'رئیس',
    'هرسال':'سال',
    'کشورهای':'کشور',
    'کشوری':'کشور',
    'کشورها':'کشور',
    'فردی':'فرد',
    'فردیت':'فرد',
    'افرادی':'فرد',
    'فردهای':'فرد',
    'فردها':'فرد',
    'نیروهای':'نیرو',
    'نیروی':'نیرو',
    'شهرهای':'شهر',
    'شهری':'شهر',
    'شهرها':'شهر',
    'مناطق':'منطقه',
    'منطقه ها':'منطقه',
    'جنگلها':'جنگل',
    'جنگلهای':'جنگل',
    'جنگلی':'جنگل',
    'دراتش':'در اتش',
    'جغرافیایی':'جغرافیا',
    'ازربایجان':'اذربایجان',
    'تصاویر':'تصویر',
    'طرح ها':'طرح',
    'طرحها':'طرح',
    'طرحهای':'طرح',
    'ابری':'ابر',
    'ابرها':'ابر',
    'کوهها':'کوه',
    'کوههای':'کوه',
    'ساحلی':'ساحل',
    'سواحل':'ساحل',
    'زمینهای':'زمین',
    'زمینها':'زمین',
    'بارندگی':'بارش',
    'بارشهای':'بارش',
    'مسولین':'مسئول',
    'مسئولان':'مسئول',
    'مشکلی':'مشکل',
    'روستاهای':'روستا',
    'روستاییان':'روستا',
    'روستاها':'روستا',
    'روستای':'روستا',
    'فعالان':'فعال',
    'سدها':'سد',
    'سدهای':'سد',
    'غذای':'غذا',
    'چاههای':'چاه',
    'تالابها':'تالاب',
    'تالابهای':'تالاب',
    'رودخانهها':'رود',
    'رودهای':'رود',
    'رودخانههای':'رود',
    'اصفهانه':'اصفهان',
    'اصفهانها':'اصفهان',
    'ایرانیان':'ایرانی',
    'ایرانیها':'ایرانی',
    'چندسال':'سال',
    'هرسال':'سال',
    'سالی':'سال',
    'سالها':'سال',
    'وبختیاری':'بختیاری',
    'کرمانشاهی':'کرمانشاه',
    'خوزستانی ':'خوزستانی',
    'سرشاخههای':'سرشاخه',
    'گرمای':'گرما',
    'دریاچهها':'دریاچه',
    'خشکسالیهای':'خشکسالی',
    'گربههای':'گربه',
    'سرچشمههای':'سرچشمه',
    'نفتی':'نفت',
    'سیلاب':'سیل',
    'سفرههای':'سفره',
    'شکارچیان':'شکار',
    'شکارچی':'شکار',
}
def replace_words(text):
    for old_word, new_word in replacement_dict.items():
        text = text.replace(old_word, new_word)
    return text

In [93]:
data['FormalTweet'] = data['FormalTweet'].apply(replace_words)

In [94]:
synonym_dict = {
    'دختر':'فرزند',
    'پسر':'فرزند',
    'بچه':'فرزند',
    'کودک':'فرزند',
    'فرد':'انسان',
    'شخص':'انسان',
    'ادم':'انسان',
    'نفر':'انسان',
    'زن':'خانم',
    'مادر':'خانم',
    'بانو':'خانم',
    'پدر':'اقا',
    'بابا':'اقا',
    'مرد':'اقا',
    'کشتن':'کشتار',
    'موقع':'وقت',
    'ساعت':'وقت',
    'حامی':'حمایت',
    'نگهداری':'حفاظت',
    'مربوط':'ارتباط',
    'ربط':'ارتباط',
    'رابطه':'ارتباط',
    'مدیریت':'مدیر',
    'مدیرکل':'مدیر',
    'شهرستان':'شهر',
    'شهری':'شهر',
    'خشکی':'خشک',
    'خشکاندن':'خشک',
    'بارندگی':'بارش',
    'بارید':'بارش',
    'ایرانی':'ایران',
    'ایرانه':'ایران'
}

In [95]:
def replaceSynonym(text):
    for old_word, new_word in synonym_dict.items():
        text = text.replace(old_word, new_word)
    return text

In [96]:
def replace_synonyms(text, synonym_dict):
    words = text.split()
    replaced_words = [synonym_dict.get(word, [word])[0] for word in words]
    return " ".join(replaced_words)

In [97]:
def replace_synonyms(text, synonym_dict):
   # Split the text into words
    words = text.split()
    # Replace each word with its synonym (if available)
    replaced_words = [synonym_dict.get(word, [word])[0] for word in words]
    # Join the words back into a string
    return " ".join(replaced_words)

In [98]:
data['FormalTweet'] = data['FormalTweet'].apply(replaceSynonym)

In [99]:
data.shape

(118299, 12)

In [102]:
data=data.drop_duplicates(subset=['FormalTweet'], keep='last')
data[~data['FormalTweet'].isnull()]

,Column1,ID,Date,Tweet,URL,Likes,Retweet,Replies,Source,FormalTweet,Keyword,language
1,1.0,1.560507e+18,2022-08-19 10:30:12,@bbrdiya تاحالا نون توموشی به کسی که اولین بار...,https://twitter.com/yourpenpalfar/status/15605...,1.0,0.0,0.0,iPhone,نان توموشی بارش بندر عالی میفهمند خاک هرمز ماه...,خاک هرمز,NaN
2,2.0,1.560269e+18,2022-08-18 18:46:43,@zahrahp1998 سرنج\nبه معنی خاک سرخ\nوایب هرمز ...,https://twitter.com/alipaydarr/status/15602694...,0.0,0.0,1.0,iPad,سرنج معنا خاک سرخ وایب هرمز,خاک هرمز,NaN
4,4.0,1.558559e+18,2022-08-14 01:28:32,@sina_mim خاک های رنگی جزیره هرمز 🙂,https://twitter.com/aarcomood/status/155855864...,1.0,0.0,1.0,Android,خاکهای رنگی جزیره هرمز,خاک هرمز,NaN
5,5.0,1.558507e+18,2022-08-13 22:04:51,@sina_mim من خاک آوردم، خاک جزیره ی هرمز,https://twitter.com/Abi_in_dream/status/155850...,1.0,0.0,0.0,iPhone,خاک خاک جزیره ی هرمز,خاک هرمز,NaN
6,6.0,1.558160e+18,2022-08-12 23:05:28,مست است زمین زیرا خورده‌ست به‌ جایِ می\nدر کاس...,https://twitter.com/Papyrustw/status/155816025...,18.0,3.0,0.0,App,مست زمین خورده میدر کاس هرمز خون دل نوشروان تا...,خاک هرمز,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
191236,72.0,1.441674e+18,2021-09-25 11:30:01,رهبران دنیا، در نشست سالانه مجموع عمومی سازمان...,https://twitter.com/hamshahrinews/status/14416...,2.0,0.0,0.0,App,رهبران دنیا نشست عمومی سازمان ملل مسئله گرماش ...,گرمایش جهانی + تغییرات اقلیم + اقلیم,fa
191237,73.0,1.441425e+18,2021-09-24 19:01:37,جوانان عضو جنبش «جمعه‌ها برای آینده» که خواستا...,https://twitter.com/IranIntlbrk/status/1441425...,10.0,0.0,1.0,NaN,جوانان عضو جنبش جمعهها خواستار مقابله جهان پدی...,گرمایش جهانی + تغییرات اقلیم + اقلیم,fa
191239,75.0,1.440404e+18,2021-09-21 23:24:26,هشدارهای تند سخنرانی امروز دبیرکل سازمان ملل ب...,https://twitter.com/bbcpersian/status/14404040...,49.0,2.0,3.0,a Studio - LiveCut,هشدارهای سخنرانی دبیرکل سازمان ملل جامعه جهان ...,گرمایش جهانی + تغییرات اقلیم + اقلیم,fa
191240,76.0,1.440025e+18,2021-09-20 23:17:38,به گفته آنتونیو گوترش، جهان با چالش‌های بی‌شما...,https://twitter.com/RadioFarda_/status/1440024...,16.0,2.0,2.0,NaN,انتونیو گوترش جهان چالشهای تغییرات اقلیم واکسی...,گرمایش جهانی + تغییرات اقلیم + اقلیم,fa
191241,77.0,1.439527e+18,2021-09-19 14:19:30,هشدار سازمان ملل: تا ۱۰ سال دیگر ۴۵% از گازهای...,https://twitter.com/bbcpersian/status/14395270...,48.0,2.0,1.0,a Studio - LiveCut,هشدار سازمان ملل سال گازهای گلخانه بکاهیم فاجع...,گرمایش جهانی + تغییرات اقلیم + اقلیم,fa

In [101]:
data.shape

(101951, 12)

In [111]:
data=data.loc[data['FormalTweet'].str.len() > 18]

In [112]:
data.shape

(93725, 12)

In [114]:
output =  '/content/drive/MyDrive/Thesis/Data/Data/Data_Paper/CleanDataset.csv'
data.to_csv(output, index=False, encoding='utf-8-sig')

In [115]:
import pandas as pd

OUTPUT_CSV = '/content/drive/MyDrive/Thesis/Data/Data/Data_Paper/Filtered_clean.csv'

# 1. Define the exact columns you want to keep
columns_to_keep = ['ID', 'FormalTweet','Date','Likes', 'Retweet', 'Replies', 'Source', 'Keyword', 'language']

# 2. Create a new DataFrame with only those columns
df_filtered = data[columns_to_keep]

# 3. Save the new DataFrame to a new CSV file
# index=False prevents pandas from writing the row numbers as an extra column
df_filtered.to_csv(OUTPUT_CSV, index=False, encoding='utf-8-sig')

print("New CSV file created successfully!")

New CSV file created successfully!